language: go

os:
    - windows
    - osx
    - linux

go:
    - 1.13.x

install:
    - go get github.com/mattn/goveralls
    - go get ./...

script:
    - go build -o /dev/null chat
    - go test -race -count 1 -cpu 1,2 -covermode=atomic -coverprofile=coverage.txt ./...

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
  - bash <(curl -s https://codecov.io/bash)
  - fi
